# Generated by Django 3.2.9 on 2021-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211128_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='play_date',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
